### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by thibmaek** [gladimdim/weather-package#5]
In keymaps/weather-package.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by LazerPanther** [comment]
+1

**Comment by gladimdim** [comment]
@thibmaek @LazerPanther thank you. I've fixed keybinding to point to atom-binding element.

Fix is available in 1.5.4 together with @thibmaek's pull request #4
